[project]
name = "ennovar"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "backend>=0.2.4.1",
    "flask>=3.1.2",
    "flask-cors>=6.0.1",
    "notebook>=7.5.0",
    "streamlit>=1.51.0",
]
